services:

  frigate:

    container_name: nvr_ia_simulador

    # TROCA A CONFIGURAÇÃO DO FRIGATE
    volumes:
      - ./frigate/config.dev.yml:/config/config.yml
      - ./midias:/media/frigate

    # opcional: mudar porta para não confundir
    ports:
      - "5001:5000"
