# ==========================================================
# CONFIGURAÇÃO FRIGATE - MODO DESENVOLVIMENTO
# SEM CÂMERA REAL
# ==========================================================

mqtt:
  host: broker_mqtt
  port: 1883

detectors:
  cpu1:
    type: cpu

# Nenhuma câmera definida
cameras: {}

version: 0.17-0
